import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  try {
    // Forward request to backend
    const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8000';

    const response = await fetch(`${backendUrl}/api/strategies`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`Backend request failed: ${response.status}`);
    }

    const data = await response.json();
    console.log('✅ Successfully connected to backend and fetched strategies');
    console.log('Strategies count:', data.strategies?.length || 0);
    return NextResponse.json(data);
  } catch (error) {
    console.error('Strategies request error:', error);
    console.error('Backend URL attempted:', process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8000');
    console.error('Full error details:', error);

    // Return mock data if backend is not available
    const mockData = {
      strategies: [
        {
          id: "aave-v3-eth",
          name: "Aave V3 Optimized",
          apy: 14.2,
          tvl: 2400000,
          risk: "Low",
          chain: "Ethereum",
          protocol: "Aave",
          category: "Lending",
          description: "Low impermanent loss with multi-protocol rebalance",
          features: ["Multi-Protocol Rebalance", "Auto-Compound", "Gas Optimized"],
          allocation: 35,
          status: "Active",
          aiOptimized: true,
          minDeposit: 100,
          maxDeposit: 100000,
          fees: 0.5,
          apyHistory: [12.8, 13.1, 13.5, 13.8, 14.0, 14.2],
          performanceScore: 92,
          volatility: 2.1,
          sharpeRatio: 1.8,
          maxDrawdown: -3.2,
          liquidityScore: 95,
          lastUpdated: "2 hours ago",
          tags: ["Popular", "Stable", "Ethereum"],
          icon: "🏦",
        },
        {
          id: "base-yield-farm",
          name: "Base Yield Farm",
          apy: 18.7,
          tvl: 1200000,
          risk: "Medium",
          chain: "Base",
          protocol: "Moonwell",
          category: "Yield Farming",
          description: "High APY with moderate risk on Base network",
          features: ["High APY", "Base Native", "Low Fees"],
          allocation: 25,
          status: "Active",
          aiOptimized: true,
          minDeposit: 50,
          maxDeposit: 50000,
          fees: 0.3,
          apyHistory: [16.2, 17.1, 17.8, 18.2, 18.5, 18.7],
          performanceScore: 88,
          volatility: 4.2,
          sharpeRatio: 1.6,
          maxDrawdown: -8.1,
          liquidityScore: 78,
          lastUpdated: "1 hour ago",
          tags: ["High Yield", "Base", "Trending"],
          icon: "🌙",
        },
        {
          id: "arbitrum-stable-pool",
          name: "Arbitrum Stable Pool",
          apy: 12.8,
          tvl: 3100000,
          risk: "Low",
          chain: "Arbitrum",
          protocol: "Curve",
          category: "Liquidity Pool",
          description: "Stable yield with minimal impermanent loss",
          features: ["Stable Returns", "Low IL Risk", "Curve Integration"],
          allocation: 20,
          status: "Active",
          aiOptimized: false,
          minDeposit: 200,
          maxDeposit: 200000,
          fees: 0.2,
          apyHistory: [11.9, 12.1, 12.3, 12.5, 12.6, 12.8],
          performanceScore: 85,
          volatility: 1.8,
          sharpeRatio: 2.1,
          maxDrawdown: -2.1,
          liquidityScore: 98,
          lastUpdated: "3 hours ago",
          tags: ["Stable", "Curve", "Arbitrum"],
          icon: "📈",
        },
        {
          id: "cross-chain-arbitrage",
          name: "Cross-Chain Arbitrage",
          apy: 22.3,
          tvl: 800000,
          risk: "High",
          chain: "Multi-Chain",
          protocol: "1inch",
          category: "Arbitrage",
          description: "AI-powered cross-chain arbitrage opportunities",
          features: ["Cross-Chain", "AI Powered", "High Returns"],
          allocation: 15,
          status: "Beta",
          aiOptimized: true,
          minDeposit: 500,
          maxDeposit: 100000,
          fees: 1.0,
          apyHistory: [19.8, 20.5, 21.1, 21.6, 22.0, 22.3],
          performanceScore: 95,
          volatility: 8.5,
          sharpeRatio: 1.2,
          maxDrawdown: -15.2,
          liquidityScore: 65,
          lastUpdated: "30 minutes ago",
          tags: ["AI", "High Risk", "Multi-Chain"],
          icon: "⚡",
        },
        {
          id: "compound-v3-strategy",
          name: "Compound V3 Strategy",
          apy: 11.5,
          tvl: 5200000,
          risk: "Low",
          chain: "Ethereum",
          protocol: "Compound",
          category: "Lending",
          description: "Conservative lending strategy with proven track record",
          features: ["Battle Tested", "Conservative", "High TVL"],
          allocation: 30,
          status: "Active",
          aiOptimized: false,
          minDeposit: 100,
          maxDeposit: 500000,
          fees: 0.4,
          apyHistory: [10.8, 11.0, 11.2, 11.3, 11.4, 11.5],
          performanceScore: 90,
          volatility: 1.5,
          sharpeRatio: 2.3,
          maxDrawdown: -1.8,
          liquidityScore: 99,
          lastUpdated: "4 hours ago",
          tags: ["Conservative", "Battle Tested", "Ethereum"],
          icon: "🏛️",
        },
        {
          id: "radiant-capital-boost",
          name: "Radiant Capital Boost",
          apy: 16.4,
          tvl: 950000,
          risk: "Medium",
          chain: "Arbitrum",
          protocol: "Radiant",
          category: "Lending",
          description: "Enhanced yields through Radiant's omnichain lending",
          features: ["Omnichain", "Boosted Rewards", "Medium Risk"],
          allocation: 18,
          status: "Active",
          aiOptimized: true,
          minDeposit: 75,
          maxDeposit: 75000,
          fees: 0.6,
          apyHistory: [14.2, 15.1, 15.6, 16.0, 16.2, 16.4],
          performanceScore: 87,
          volatility: 3.8,
          sharpeRatio: 1.7,
          maxDrawdown: -6.5,
          liquidityScore: 82,
          lastUpdated: "1 hour ago",
          tags: ["Omnichain", "Boosted", "Arbitrum"],
          icon: "💎",
        },
      ],
      summary: {
        totalStrategies: 6,
        averageAPY: 15.8,
        totalTVL: 13650000,
        aiOptimizedCount: 4,
        categoryBreakdown: {
          "Lending": 3,
          "Yield Farming": 1,
          "Liquidity Pool": 1,
          "Arbitrage": 1,
        },
        chainBreakdown: {
          "Ethereum": 2,
          "Base": 1,
          "Arbitrum": 2,
          "Multi-Chain": 1,
        },
        riskBreakdown: {
          "Low": 3,
          "Medium": 2,
          "High": 1,
        },
      },
    };

    return NextResponse.json(mockData);
  }
}